CapaPresentacionAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using CapaNegocio;
using CapaEntidad;

//los datos vienen de CAPA DE NEGOCIO

namespace CapaPresentacionAdmin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarUsuarios()
        {
            List<Usuario> oLista = new List<Usuario>();

             oLista = new CN_Usuarios().Listar();

                
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        public JsonResult GuardarUsuario(Usuario objeto)
        {
            object resultado; // permite guardar cualquier tipo de valor 
            string mensaje = string.Empty;

            if (objeto.IdUsuario == 0)
            {
                // llamamos la capa de negocio y instanciamos la clase registrar  
                resultado = new CN_Usuarios().Registrar(objeto, out mensaje);

            }
            else
            {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);

            }


            return Json(new {resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;


            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }



    }
}

CapaPresentacionAdmin/Controllers/MantenedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmin.Controllers
{
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }

        public ActionResult Marca()
        {
            return View();
        }

        public ActionResult Producto()
        {
            return View();
        }

        
    }
}

CapaPresentacionAdmin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CapaPresentacionAdmin/Views/Home/Usuarios.cshtml
@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuarios</h2>
<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Usuarios</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> Lista de Usuarios
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-success" onclick="abrirModal(null)">Crear Nuevo Usuario</button>
            </div>
        </div>

        <hr />
        <table id="tabla" class="table table-dark table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Correo</th>
                    <th>Activo</th>
                    <th></th>
                </tr>


            </thead>
            <tbody>
            </tbody>
        </table>


    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Registrar Nuevo Usuario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                <input id="txtId" type="hidden" value="0" />
                <div class="row g-2">

                    <div class="col-sm-6">
                        <label for="txtnombres" class="form-label">Nombres</label>
                        <input type="text" class="form-control" id="txtnombres">
                    </div>
                    <div class="col-sm-6">
                        <label for="txtapellidos" class="form-label">Apellidos</label>
                        <input type="text" class="form-control" id="txtapellidos">
                    </div>
                    <div class="col-sm-6">
                        <label for="txtcorreo" class="form-label">Correo</label>
                        <input type="email" class="form-control" id="txtcorreo" placeholder="Ingrese su Correo">
                    </div>


                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select class="form-select" id="cboactivo" aria-label="Default select example">
                            <option value="1">Activo</option>
                            <option value="0">Inactivo</option>

                        </select>
                    </div>
                    


                </div>
                <div class="row mt-3">
                    <div class="col-12">

                        <div id="mensaje_error" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>

                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()" >Guardar</button>
            </div>
        </div>
    </div>
</div>




@section scripts{
    <script>
        var tabladata;
        var filaSeleccionada;
        /*---------------------------------contiene toda la imformacion de la tabla ----------------------*/
        jQuery.ajax({
            url:'@Url.Action("ListarUsuarios", "Home")',
            type: "GET",
            dataType: "json",
            contentType: "aplication/json; charset=utf-8",
            success: function (data) {

                console.log(data)
            }
        })

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarUsuarios", "Home")',
                type: "GET",
                dataType: "json"
            },
            "columns": [

                { "data": "Nombres" },
                { "data": "Apellidos" },
                { "data": "Correo" },
                {
                    "data": "Activo", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-primary">Activo</span>'
                        } else {
                            return '<span class="badge bg-danger">Inactivo</span>'
                        }

                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-outline-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-outline-danger btn-sm ms-3 btn-eliminar "><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }


            ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"
            }
            /*----------------------------------------------------------------------------------------*/
        });
        function abrirModal(json) {

            /*------------------ traer los usuarios para editar--------------------------------------*/

            $("#txtId").val(0);
            $("#txtnombres").val("");
            $("#txtapellidos").val("");
            $("#txtcorreo").val("");
            $("#cboactivo").val("");



            $("#mensaje_error").hide();




            if (json != null) {

                $("#txtId").val(json.IdUsuario);
                $("#txtnombres").val(json.Nombres);
                $("#txtapellidos").val(json.Apellidos);
                $("#txtcorreo").val(json.Correo);
                $("#cboactivo").val(json.Activo == true ? 1 : 0);

            }

            /*------------------ -----------------------------------------------------------------*/

            $("#FormModal").modal("show");



        }
        /*----------------------------------------------EVENTO BOTON EDITAR -----------------------------------------*/
        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            abrirModal(data)

        })


        /*----------------------------------------------EVENTO BOTON ELIMINAR -----------------------------------------*/
        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var usuarioSeleccionado= $(this).closest("tr");

            var data = tabladata.row(usuarioSeleccionado).data();

            swal({
                title: "Estas seguro?",
                text: "Deseas Eliminar el Usuario?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si, Deseo Eliminar",
                cancelButtonText: "No!",
                closeOnConfirm: true
            },
                function () {

                    jQuery.ajax({
                    url: '@Url.Action("EliminarUsuario", "Home")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdUsuario }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            debugger;
                            if (data.resultado) {
                                tabladata.row(usuarioSeleccionado).remove().draw();
                            } else {
                                swal("No se pudo eliminar ",data.mensaje,"error")
                            }
                        },
                        error: function (error) {
                            console.log(error)
                        },
    
                    });
                
            });





            console.log(data);

        })

        /*------------------------------------------------------GUARDAR -----------------------------------------*/

        function Guardar() {

            var Usuario = {
                IdUsuario: $("#txtId").val(),
                Activo: $("#cboactivo").val() == 1 ? true: false,
                Apellidos: $("#txtapellidos").val(),
                Correo: $("#txtcorreo").val(),
                Nombres: $("#txtnombres").val()

            }

            /*----------Aqui sabemos si es para editar un usuario o guardar un nuevo usuario---------------*/

            jQuery.ajax({
                url: '@Url.Action("GuardarUsuario", "Home")',
                type: "POST",
                data: JSON.stringify({ objeto: Usuario }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide");
                    //resive el return de GuardarUsuario

                   // debugger;
                    // USUARIO NUEVO
                    if (Usuario.IdUsuario == 0) {

                        if (data.resultado != 0) {
                            Usuario.IdUsuario = data.resultado;

                            tabladata.row.add(Usuario).draw(false);


                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensaje_error").text(data.mensaje);
                            $("#mensaje_error").show();
                        }



                        // EDITAR USUARIO
                    } else {

                        if (data.resultado) {




                            tabladata.row(filaSeleccionada).data(Usuario).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensaje_error").text(data.mensaje);
                            $("#mensaje_error").show();
                        }


                    }


                },
                error: function (error) {

                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensaje_error").text("error ajax");
                    $("#mensaje_error").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Por Favor Espere...",
                        size: 14
                    })
                },
            });






            /*-------------------------------------------------------------------------------------*/

        }





    </script>


}

CapaPresentacionAdmin/Views/Mantenedor/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categoria</h2>

CapaPresentacionAdmin/Views/Mantenedor/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marca</h2>

CapaPresentacionAdmin/Views/Mantenedor/Producto.cshtml
@{
    ViewBag.Title = "Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Producto</h2>

CapaPresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">MI TIENDA</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo del Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar Sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">


                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users-cog"></i></div>
                            Usuarios
                        </a>
                        @*<div class="sb-sidenav-menu-heading">Interface</div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
            Layouts
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
            </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            Pages
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                    Authentication
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="login.html">Login</a>
                        <a class="nav-link" href="register.html">Register</a>
                        <a class="nav-link" href="password.html">Forgot Password</a>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                    Error
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="401.html">401 Page</a>
                        <a class="nav-link" href="404.html">404 Page</a>
                        <a class="nav-link" href="500.html">500 Page</a>
                    </nav>
                </div>
            </nav>
        </div>*@

                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Categoria","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" href="@Url.Action("Marca","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" href="@Url.Action("Producto","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <!--------------- esto es lo unico que va a cambiar  ------------------------------------------------------->
                    @RenderBody()    @*con este comando estamos diciendo que aqui es donde se va a mostrar nuestras pestañas nuevas*@



                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>










    @**@

    @*<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@








    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>